### ISSUE TITLE
Unclear on usage

### ISSUE THREAD

**Issue by CyberMew** [mykolaharmash/hyntax#38]
So if I just want to load a html string, and have it look for #someClassName or .someId to get their html text value, how do I use this?

**Comment by mykolaharmash** [comment]
Hi. You are probably looking for something that support CSS selectors, like `querySelection()` in DOM API. Hyntax is just an HTML parser which converts string into js object with a tree structure, meaning you'd have to walk the tree yourself in order to find a tag or other element.

For example:
```
const { tokens } = tokenize('<div class="some-class">Hello</div>')
const { ast } = constructTree(tokens)
```

`ast` will contain object like this (I removed irrelevant bits):

```
{
  "nodeType": "document",
  "content": {
    "children": [
      {
        "nodeType": "tag",
        "content": {
          "name": "div",
          "attributes": [
            {
              "key": {
                "type": "token:attribute-key",
                "content": "class",
                "startPosition": 5,
                "endPosition": 9
              },
              "value": {
                "type": "token:attribute-value",
                "content": "some-class",
                "startPosition": 12,
                "endPosition": 21
              }
            }
          ],
          "selfClosing": false,
          "children": [
            {
              "nodeType": "text",
              "content": {
                "value": {
                  "type": "token:text",
                  "content": "Hello",
                  "startPosition": 24,
                  "endPosition": 28
                }
              }
            }
          ]
        }
      }
    ]
  }
}
```

So you see that there is one tag nested within the document, the tag has one attribute with a key `class` and value `some-class`. At this point it's up to you how you want to traverse this object either by writing a simple helper functions or using external library.

Home it helps, let me know if it's still unclear.
